- name: variables to print
  hosts: web

  vars:
    COURSE: "DevOps"
    DURATION: "120HRS"
    TIMINGS: "MOR 12'O CLOCK"
    TRAINER: "SHIVA"

  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "Hi I am learning {{ COURSE }}, DURATION is: {{ DURATION }}, TIMINGS is: {{ TIMINGS }}, TRAINER: {{ TRAINER }}"
