#try to not change anything in source files. because we may have accidentally changes others so we have to maintain the the separate varible file.
- name: variables from file
  hosts: web

  vars_files:
    - vars.yaml

  tasks:
    - name: print the course information
      ansible.builtin.debug:
        msg: "Hi I am learning {{ COURSE }}, DURATION is: {{ DURATION }}, TIMINGS is: {{ TIMINGS }}, TRAINER: {{ TRAINER }}"
