#args passed from the terminal
- name: variables to print
  hosts: web
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "Hello {{ NAME }}, Good {{ GREETINGS }}, Welcome {{ CEREMONY }}"
