- name: Devops course information
  hosts: local
  connection: local #for local host
  vars:
    course: "DevOps with AWS" #string
    duration: 120HRS #int/float
    topics: #list
    - Linux
    - Shell
    - Ansible
    - Terraform
    - AWS
    - K8
    live: true #Boolean
    tools: #map/dictionary
      ci: jenkins
      cm: ansible
      cloud: AWS
      AWS: #list
      - IAM
      - S3
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi I am learning {{ course }}, with duration: {{ duration }}, topics are: {{ topics }}, and live: {{ live }}, tools are: {{ tools }}"