- name: command vs shell
  hosts: local
  connection: local
  tasks:
    - name: execute the shell
      ansible:builtin.shell: "ls -ltr > /tmp/ouput.txt" #login to the server and execute command inside but command module is just issues command. command line secure than shell.

    - name: check the process
      ansible.builtin.debug: ps -ef | grep ssh
      register: ouput



